### PR TITLE
switched from `React.PropTypes` to the `prop-types` package

### PR DESCRIPTION
**Pull request by travi**

### CODE REVIEW

**Comment by elijahmanor** [comment]
Thanks!

**Comment by travi** [comment]
no problem. this was blocking an upgrade to react v16. 

if you could publish this, i'll confirm that things are all ok with react v16 and can send another PR to include `|| ^16.0.0` for the `react` dependency. 

if you don't want to push it out to everyone before both changes, you could publish with a tag that isnt `latest` for this step.

**Comment by elijahmanor** [comment]
spectacle-terminal 0.5.0 published 🎉

**Comment by travi** [comment]
thanks! things seem to work well other than what i logged in #5

**Pull request merged**
